### ISSUE TITLE
LNbits "master" branch was renamed to "main"

### ISSUE THREAD

**Issue by callebtc** [cryptoteun/awesome-lnbits#11]
Hi! Awesome list!

Some of the extension links are 404 because they assume the old branch name (like the Ngrok extension).

The "master" branch is now deprecated and should be adjusted accordingly. 

Thanks!

**Comment by LightRider5** [comment]
- [LNURLw](https://github.com/lnbits/lnbits-legend/tree/master/lnbits/extensions/lnurlw) - Mint LNURL-withdraws (Pull payments links, faucets, etc) is also a 404.

**Comment by btcteun** [comment]
Thanks, it should be fixed now.
